env:
  browser: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins: ["prettier"]
rules:
  prettier/prettier: "error"
  quotes: ["error", "double", { "allowTemplateLiterals": true }]
  import/extensions: ["error", { "mjs": "ignorePackages","js": "ignorePackages" }]
  no-console: off
